name: macOS build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install wkhtmltopdf
      run: brew install wkhtmltopdf

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TestPDFs
        path: '**/*.pdf'