name: Windows manual tests

on: workflow_dispatch

jobs:

  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Install wkhtmltopdf
      run: choco install wkhtmltopdf

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: stable

    - name: Test
      run: go test -v .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: TestPDFs
        path: '**/*.pdf'
